name: i_billing
description: "Simple contract app"

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # icons
  cupertino_icons: any

  # network
  http: any
  http_interceptor: any

  # ui component
  flutter_slidable: any
  animations: any
  scrollable_positioned_list: any
  flutter_multi_formatter: ^2.12.4
  url_launcher: ^6.2.4
  lottie: any
  intl: ^0.17.0
  feature_discovery: any
  flutter_staggered_animations: any
  animated_text_kit: any


  # state management
  flutter_bloc: any

  # objects equals
  equatable: any

  # data base
  shared_preferences: ^2.0.5

  # sign in
  google_sign_in: any
  flutter_facebook_auth: any

  # firebase
  firebase_core: ^2.25.4
  firebase_auth: any
  firebase_dynamic_links: ^5.4.14
  firebase_database: any

  # dependency injection
  get_it: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fonts/monda/
    - assets/fonts/poppins/
    - assets/fonts/ubuntu/
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
    - family: Monda
      fonts:
        - asset: assets/fonts/monda/Monda-Medium.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Regular.ttf
        - asset: assets/fonts/ubuntu/Ubuntu-Medium.ttf
